version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-sports-reels
    restart: always
    ports:
      - 3002:3000

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules
